const ActivityActionTypes = {
    SET_SELECTED_ACTIVITY: 'SET_SELECTED_ACTIVITY',
    SET_EDIT_MODE: 'SET_EDIT_MODE',

    FETCH_ACTIVITIES_START: 'FETCH_ACTIVITIES_START',
    FETCH_ACTIVITIES_SUCCESS: 'FETCH_ACTIVITIES_SUCCESS',

    EDIT_EXISTING_ACTIVITY_START: 'EDIT_EXISTING_ACTIVITY_START',
    EDIT_EXISTING_ACTIVITY_SUCCESS: 'EDIT_EXISTING_ACTIVITY_SUCCESS',

    ADD_ACTIVITY_START: 'ADD_ACTIVITY_START',
    ADD_ACTIVITY_SUCCESS: 'ADD_ACTIVITY_SUCCESS',

    REMOVE_EXISTING_ACTIVITY_START: 'REMOVE_EXISTING_ACTIVITY_START',
    REMOVE_EXISTING_ACTIVITY_SUCCESS: 'REMOVE_EXISTING_ACTIVITY_SUCCESS',

    FETCH_FAILURE: 'FETCH_FAILURE',


};

export default ActivityActionTypes;
