const ActivityActionTypes = {
    SET_SELECTED_ACTIVITY: 'SET_SELECTED_ACTIVITY',
    FETCH_ACTIVITIES_START: 'FETCH_ACTIVITIES_START',
    FETCH_ACTIVITIES_SUCCESS: 'FETCH_ACTIVITIES_SUCCESS',
    FETCH_ACTIVITIES_FAILURE: 'FETCH_ACTIVITIES_FAILURE'
};

export default ActivityActionTypes;
