const ActivityActionTypes = {
    SET_SELECTED_ACTIVITY: 'SET_SELECTED_ACTIVITY',
    SET_EDIT_MODE: 'SET_EDIT_MODE',
    FETCH_ACTIVITIES_START: 'FETCH_ACTIVITIES_START',
    FETCH_ACTIVITIES_SUCCESS: 'FETCH_ACTIVITIES_SUCCESS',
    FETCH_ACTIVITIES_FAILURE: 'FETCH_ACTIVITIES_FAILURE',
    EDIT_EXISTING_ACTIVITY: 'EDIT_EXISTING_ACTIVITY',
    ADD_ACTIVITY: 'ADD_ACTIVITY',
    REMOVE_EXISTING_ACTIVITY: 'REMOVE_EXISTING_ACTIVITY'
};

export default ActivityActionTypes;
